### ISSUE TITLE
Prestiging error due to translating

### ISSUE THREAD

**Issue by Firescoutt** [Firescoutt/BattleBanana#1]
The prestige process itself does not break and the player does actually prestige and get award, its just the message the bot sends at the very end to say they have prestige thats being a fucking prick

```py
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "run.py", line 231, in on_message
    await events.on_message_event(message)
  File "/root/python/BattleBananaTest/dueutil/events.py", line 95, in on_message_event
    await command_event(ctx)
  File "/root/python/BattleBananaTest/dueutil/events.py", line 74, in __call__
    await command(ctx, *args)
  File "/root/python/BattleBananaTest/dueutil/commands.py", line 99, in wrapped_command
    await command_func(ctx, *command_args, **get_command_details(ctx, **details))
  File "/root/python/BattleBananaTest/dueutil/commands.py", line 203, in wrapped_command
    await command_func(ctx, **details)
  File "/root/python/BattleBananaTest/dueutil/botcommands/player.py", line 363, in prestige
    await translations.say(ctx, "player:pretige:SUCCESS", user.presitge_level)
AttributeError: 'Player' object has no attribute 'presitge_level'
```

**Comment by Firescoutt** [comment]
fix this later because lazy
